- title: Morph: Efficient File-Lifetime Redundancy Management for Cluster File Systems
  authors:
    - Timothy Kim
    - Sanjith Athlur
    - Saurabh Kadekodi
    - Francisco Maturana
    - Dax Delvira
    - Arif Merchant
    - Gregory R. Ganger
    - K. V. Rashmi
  publisher: Symposium for Operating Systems Principles
  link: https://www.pdl.cmu.edu/ftp/Storage/Morph_Final.pdf
